import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter()
  const [loading, setLoading] =  useState(false)
  const [data, setData]:any = useState(null)
  const [openMenu, setOpenMenuu] = useState(false)

  useEffect(() => {
    setLoading(true)

    fetch('https://pokeapi.co/api/v2/pokemon')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerWrapper}>
        <img className={styles.menu} onClick={() => setOpenMenuu(!openMenu)} src='/icons-menu-rounded.png' />
        <img className={styles.logo} onClick={() => router.push('/')} src='/pokemon-logo.png'/>
      </div>
      <main className={styles.main}>
        {
          loading ? <div className={styles.ldsRing}><div></div><div></div><div></div><div></div></div>
          : (
            <div className={styles.listContainer}>
              {
                data && data.results && data.results.map((result:any) => (
                  <div onClick={() => router.push(`/pokemon/${result.name}`)} className={styles.list} key={result.name}>
                    <h1 >{result.name}</h1>
                  </div>
                ))
              }
            </div>
          )
        }
        {
          openMenu && (
            <div className={styles.menuWrapper}>
              <div className={styles.menuContainer}>
                <h3>Menu</h3>
                <div className={styles.menuListContainer}>
                  <p className={styles.menuList} onClick={() => router.push('/saved-pokemon')}>Saved Pokemon</p>
                </div>
              </div>
            </div>
          )
        }
      </main>
    </div>
  )
}

export default Home
