import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'

import { useCookies } from 'react-cookie'

import styles from '../../styles/Detail.module.css'

const Detail: NextPage = () => {
  const router = useRouter()
  const { name } = router.query
  const [loading, setLoading] =  useState(false)
  const [data, setData]:any = useState(null)
  const [openModal, setOpenModal] = useState(false)
  const [nickname, setNickname] = useState('')
  const [cookies, setCookie]:any = useCookies([""])
  const [openMenu, setOpenMenu] = useState(false)

  const onClickSave = (e:any) => {
    e.preventDefault()
    setCookie(`${name}`, nickname)
    setOpenModal(false)
  }

  useEffect(() => {
    setLoading(true)

    if (router.isReady) {
      fetch(`https://pokeapi.co/api/v2/pokemon/${name}`)
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
    }
  }, [])

  const onChangeNickname = (e :any) => {
    e.preventDefault()
    setNickname(e.target.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{name || ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerWrapper}>
        <img className={styles.menu} onClick={() => setOpenMenu(!openMenu)} src='/icons-menu-rounded.png' />
        <img className={styles.logo} onClick={() => router.push('/')} src='/pokemon-logo.png'/>
      </div>
      <main className={styles.main}>
        {
          loading && <div className={styles.ldsRing}><div></div><div></div><div></div><div></div></div>
        }
        {
          !loading && data && (
            <div className={styles.container}>
              {
                (
                  <>
                    <h1>{name}</h1>
                    <img src={data ? data.sprites.front_default : ''}/>
                    <div>
                      <h2>ABILITIES</h2>
                      {
                        data.abilities.map((ability:any) => <p key={ability.ability.name}>{ability.ability.name}</p>)
                      }
                    </div>
                    <div className={styles.button} onClick={() => setOpenModal(true)}>Catch</div>
                  </>
                )
              }
            </div>
          )
        }
        {
          openModal && (
            <div className={styles.modal}>
              <form className={styles.form} onSubmit={onClickSave}>
                <h1>Success</h1>
                <p>Please give a nickname</p>
                <input
                  required
                  className={styles.input}
                  onChange={onChangeNickname}/>
                <button type="submit" className={styles.buttonModal}>Save</button>
              </form>
            </div>
          )
        }
        {
          openMenu && (
            <div className={styles.menuWrapper}>
              <div className={styles.menuContainer}>
                <h3>Menu</h3>
                <div className={styles.menuListContainer}>
                  <p className={styles.menuList} onClick={() => router.push('/saved-pokemon')}>Saved Pokemon</p>
                </div>
              </div>
            </div>
          )
        }
      </main>
    </div>
  )
}

export default Detail
