import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../../styles/Home.module.css'
import { useCookies } from 'react-cookie'

const SavedPokemon: NextPage = () => {
  const router = useRouter()
  const [loading, setLoading] =  useState(false)
  const [openMenu, setOpenMenuu] = useState(false)
  const [cookies, setCookie, removeCookie]:any = useCookies([""])
  // const [savedPokemons, setSavedPokemons] = useState([''])
  let savedPokemons = Object.keys(cookies)

  const onClickRelease = async (data:any) => {
    removeCookie(data)
    router.reload()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Saved Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerWrapper}>
        <img className={styles.menu} onClick={() => setOpenMenuu(!openMenu)} src='/icons-menu-rounded.png' />
        <img className={styles.logo} onClick={() => router.push('/')} src='/pokemon-logo.png'/>
      </div>
      <main className={styles.main}>
        {
          loading ? <div className={styles.ldsRing}><div></div><div></div><div></div><div></div></div>
          : (
            <div className={styles.listContainer}>
              {
                savedPokemons.map((data: any) => cookies[data] && (
                  <div className={styles.list} key={data}>
                    <h1>{cookies[data]}</h1>
                    <div onClick={() => onClickRelease(data)} className={styles.releaseButton}>Release</div>
                  </div>
                ))
              }
            </div>
          )
        }
        {
          openMenu && (
            <div className={styles.menuWrapper}>
              <div className={styles.menuContainer}>
                <h3>Menu</h3>
                <div className={styles.menuListContainer}>
                  <p className={styles.menuList} onClick={() => router.push('/saved-pokemon')}>Saved Pokemon</p>
                </div>
              </div>
            </div>
          )
        }
      </main>
    </div>
  )
}

export default SavedPokemon
